#!/bin/bash
#
# Usage: git-co
#
# Commits changes to the branch
#

ref=$(git symbolic-ref HEAD 2> /dev/null) || exit 0
branch="${ref#refs/heads/}"

#remote="origin"
#branch=$1

#if [ -z $branch ]; then
#  echo "Usage: $0 [branchname]"
#  exit 1
#fi

echo "git commit -m $branch"
exit 0
