#!/bin/bash
#
# Usage: git-cu
#
# Catches up with the changes done (remotely) to the trunk..
# .. and merges those changes into the branch
#
remote="origin"
ref=$(git symbolic-ref HEAD 2> /dev/null) || exit 0
branch="${ref#refs/heads/}"
parent="master"
#parent="dev"

git checkout $parent
git pull $remote $parent
git checkout $branch
git rebase $parent
exit 0
