#!/bin/bash
#
# Usage: git-done
#
# Clean development artifacts of the <branch>
#
remote="origin"
ref=$(git symbolic-ref HEAD 2> /dev/null) || exit 0
branch="${ref#refs/heads/}"

git checkout master
git fetch $remote 
git reset --hard $remote/master
git branch -d $branch
